// Generated by scripts/generate-lqip.mjs — do not edit by hand.
// Re-run with `npm run lqip` when hero images change.

export const LQIP: Record<string, string> = {
  "/screenshots/welcome.jpg": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAAAQBgCdASoUAC0APxF4rVIsJyOisBVaqYAiCUAXYAXN3KHWdpXEoFtj6F8Y0qVtfYMEhjrQt967UAAA/I/8m+l1LCB0jVkLTQ7EEHol82wRUxwX4ZVbqxX8VC5lNZIvzQjnp5PIzyl4oCn2FWY8G1lhAZD7ocPlQ9RfzQiXUE+UCSWZwTlOnaxW95CZmz2FPzE/XEHHmznI6lep+a4jNW4JDeG4bMAZ6eUwaizwplXs2d8KujQIsLrJWZsZ5y9FJsUJZEu8EAA=",
  "/screenshots/dashboard.jpg": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADQBQCdASoUAC0APxF+tlUsKCSjJWsxgCIJZwDOSf/gUysgqsvc+ouYd7shS7YtLdl4zWXdeXgAAP7xgDCG4TfqLpWyKPa/dqhfltBK2ob7Kv6Q0E9M2lboK9UAthPzhSG1joqhnLRoBYmBjmAlYBpYptIKGA3lY1MYIaD2NMYFyeciWg03ShhFUnohDiDvEjsFenVodoufLmbfnwYhpa73UkvEMjbFIHZ6w0ukKYxiJp9WRd8U/PzgQmUpGwwCb7wPmrkg3m+8jg06x6ZoAA==",
  "/screenshots/nutrition.jpg": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBgCdASoUAC0APwlqr1ArpaQisAqpcCEJQBf4P/wGxMIv3JphuSYoXXPpSdViW88oaIBSJp5lUoAA/uX3gDhUEI5t+u9j9rmvHPxXe0AganwMsShavLeDvPSKBOlyy7VCERFnUMuJHzoJcNUZVIcSIjZ22BuGfOHJ+ZnBypC5UwXUaDPSi1/bofu6Cj0JVg3GSx2dpdnTuy8DWYrJA/lwBVBaPkoAtPK3IVMMVR8kifiK+hl7+sLaPIlDUAAA"
};
