#!/usr/bin/env node
/**
 * Generate LQIP (low-quality image placeholder) data URIs for hero images.
 *
 * Outputs a TypeScript module at src/lib/image-lqip.ts that maps image paths
 * to base64-encoded tiny blurred WebP data URIs. Components use these as the
 * `blurDataURL` prop on next/image so the LCP image fades in over a tinted
 * blur instead of a hard pop.
 *
 * Idempotent: re-run with `npm run lqip` after adding new heroes.
 */

import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(fileURLToPath(import.meta.url), '../../');

// Top-of-page images that benefit from a blur placeholder.
// Keep this list lean — LQIP shipping cost is the base64 string per entry.
const TARGETS = [
  '/screenshots/welcome.jpg',
  '/screenshots/dashboard.jpg',
  '/screenshots/nutrition.jpg',
];

async function lqipDataUri(src) {
  const abs = path.join(ROOT, 'public', src);
  const buf = await sharp(abs)
    .resize(20, null, { fit: 'inside' }) // ~20 px wide; enough to convey color + composition
    .webp({ quality: 30 })
    .toBuffer();
  return `data:image/webp;base64,${buf.toString('base64')}`;
}

(async () => {
  const map = {};
  for (const t of TARGETS) {
    map[t] = await lqipDataUri(t);
    console.log(`  ${t}  → ${map[t].length} bytes`);
  }
  const out = `// Generated by scripts/generate-lqip.mjs — do not edit by hand.
// Re-run with \`npm run lqip\` when hero images change.

export const LQIP: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;
  await fs.writeFile(path.join(ROOT, 'src/lib/image-lqip.ts'), out, 'utf8');
  console.log(`\nwrote src/lib/image-lqip.ts (${TARGETS.length} entries)`);
})();
